"""create_daily_order_reports_table_lab8

Revision ID: 0b58c094fab3
Revises: 88204b1c4f4e
Create Date: 2025-12-14 14:00:50.897450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b58c094fab3'
down_revision: Union[str, Sequence[str], None] = '88204b1c4f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_order_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_at', sa.Date(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('count_product', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_order_reports_report_at'), 'daily_order_reports', ['report_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_order_reports_report_at'), table_name='daily_order_reports')
    op.drop_table('daily_order_reports')
    # ### end Alembic commands ###
