"""empty message

Revision ID: bede223393e2
Revises: bdecbeb4621b
Create Date: 2025-10-26 15:50:57.691056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bede223393e2'
down_revision: Union[str, Sequence[str], None] = 'bdecbeb4621b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('province', sa.String(), nullable=False))
    op.add_column('addresses', sa.Column('zip_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'zip_code')
    op.drop_column('addresses', 'province')
    # ### end Alembic commands ###
